- id: 'omega_up'
  alias: 'Notify UJ on telegram when O.M.E.G.A starts'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: notify.telegram_ujg
    data:
      message: 'O.M.E.G.A has started successfully'

# - id: 'omega_down'
#   alias: 'Notify UJ on telegram when O.M.E.G.A stops'
#   trigger:
#   - event: shutdown
#     platform: homeassistant
#   condition: []
#   action:
#   - service: notify.telegram_ujg
#     data:
#       message: 'O.M.E.G.A has stopped'

- id: 'sid_home_yes'
  alias: 'Notify UJ on telegram when sid comes home'  
  trigger:
  - platform: state
    entity_id: device_tracker.iphone_xs_max_cable_rcn_com
    from: not_home
    to: home
  condition: 
  - condition: time
    after: '15:00:00'
    before: '23:00:00'
  action:
  - service: notify.telegram_ujg
    data:
      message: 'Hey, Sid is home!!!'

- id: 'boys_all_home'
  alias: 'Notify UJ on telegram when everyone is home'  
  trigger:
  - platform: template
    value_template: "{% if is_state('device_tracker.ujg_cable_rcn_com', 'home') %}true{% endif %}"
  condition: 
  - condition: state
    entity_id: device_tracker.fc_2a_9c_a8_9c_85
    state: home
  - condition: state
    entity_id: device_tracker.iphone_xs_max_cable_rcn_com
    state: home
  - condition: state
    entity_id: device_tracker.oneplus6tsingle_cable_rcn_com
    state: home
  - condition: state
    entity_id: device_tracker.galaxy_s8_cable_rcn_com
    state: home
  action:
  - service: notify.telegram_ujg
    data:
      message: 'Holaaaa! Everyone is home!!!'


